files:
    "/sbin/appstart" :
        mode: "000755"
        owner: webapp
        group: webapp
        content: |
            #!/usr/bin/env bash
            JAR_PATH=/var/app/current/application.jar

            # run app
            killall java
            java -Dfile.encoding=UTF-8 -jar $JAR_PATH

    "/etc/nginx/conf.d/proxy.conf":
      mode: "000644"
      owner: root
      group: root
      content: |
        client_max_body_size 16M;